import { Project, VideoFile, VideoAnalysis, Scene } from "@/types";

const mockScenes: Scene[] = [
  {
    scene_number: 1,
    start_time: "00:00:00",
    end_time: "00:02:15",
    description: "Вступительные титры, панорама города",
    risk: null,
    risk_level: null,
    probability: null,
    reason: null,
    quote: null,
    text_in_frame: null,
    recommendation: null,
  },
  {
    scene_number: 2,
    start_time: "00:02:15",
    end_time: "00:05:30",
    description: "Персонажи обсуждают план в баре, на столе бутылки алкоголя",
    risk: "alcohol",
    risk_level: "info",
    probability: 0.6,
    reason: "Демонстрация алкогольной продукции в кадре без негативной коннотации",
    quote: null,
    text_in_frame: null,
    recommendation: "blur",
  },
  {
    scene_number: 3,
    start_time: "00:05:30",
    end_time: "00:08:45",
    description: "Диалог персонажей в офисе",
    risk: null,
    risk_level: null,
    probability: null,
    reason: null,
    quote: null,
    text_in_frame: null,
    recommendation: null,
  },
  {
    scene_number: 4,
    start_time: "00:08:45",
    end_time: "00:12:20",
    description: "Персонаж использует нецензурную лексику в диалоге с коллегой",
    risk: "profanity",
    risk_level: "critical",
    probability: 0.95,
    reason: "Многократное использование ненормативной лексики в диалоге",
    quote: "****** ты что, совсем ******?! Я же тебе ******* говорил!",
    text_in_frame: null,
    recommendation: "mute",
  },
  {
    scene_number: 5,
    start_time: "00:12:20",
    end_time: "00:15:00",
    description: "Сцена драки в переулке, удары крупным планом",
    risk: "violence",
    risk_level: "critical",
    probability: 0.88,
    reason: "Детальная демонстрация физического насилия с крупными планами ударов",
    quote: null,
    text_in_frame: null,
    recommendation: "shorten",
  },
  {
    scene_number: 6,
    start_time: "00:15:00",
    end_time: "00:18:30",
    description: "Персонаж курит на балконе, разговаривает по телефону",
    risk: "smoking",
    risk_level: "warning",
    probability: 0.72,
    reason: "Длительная демонстрация курения без предупреждения",
    quote: null,
    text_in_frame: null,
    recommendation: "shorten",
  },
  {
    scene_number: 7,
    start_time: "00:18:30",
    end_time: "00:22:00",
    description: "Граффити на стене с запрещённой символикой",
    risk: "forbidden_symbols",
    risk_level: "critical",
    probability: 0.91,
    reason: "В кадре видна стена с символикой, которая может быть классифицирована как экстремистская",
    quote: null,
    text_in_frame: "Надпись содержит запрещённую символику",
    recommendation: "blur",
  },
  {
    scene_number: 8,
    start_time: "00:22:00",
    end_time: "00:25:07",
    description: "Романтическая сцена между персонажами",
    risk: null,
    risk_level: null,
    probability: null,
    reason: null,
    quote: null,
    text_in_frame: null,
    recommendation: null,
  },
  {
    scene_number: 9,
    start_time: "00:25:07",
    end_time: "00:26:42",
    description: "Персонаж произносит речь, оправдывающую противоправные действия",
    risk: "crime_glorification",
    risk_level: "critical",
    probability: 0.85,
    reason: "Монолог персонажа содержит прямое оправдание и романтизацию преступных действий",
    quote: "Иногда нужно нарушить закон, чтобы восстановить справедливость. Настоящие герои не боятся переступить черту.",
    text_in_frame: null,
    recommendation: "remove",
  },
  {
    scene_number: 10,
    start_time: "00:26:42",
    end_time: "00:30:00",
    description: "Персонаж демонстрирует употребление наркотических веществ",
    risk: "drugs",
    risk_level: "critical",
    probability: 0.93,
    reason: "Прямая демонстрация употребления наркотических веществ без негативных последствий",
    quote: null,
    text_in_frame: null,
    recommendation: "remove",
  },
  {
    scene_number: 11,
    start_time: "00:30:00",
    end_time: "00:33:15",
    description: "Финальная сцена, закат, персонажи прощаются",
    risk: null,
    risk_level: null,
    probability: null,
    reason: null,
    quote: null,
    text_in_frame: null,
    recommendation: null,
  },
  {
    scene_number: 12,
    start_time: "00:33:15",
    end_time: "00:35:00",
    description: "Надпись в кадре с рекламой алкогольной продукции",
    risk: "alcohol",
    risk_level: "warning",
    probability: 0.68,
    reason: "Текст в кадре содержит рекламу алкогольного бренда",
    quote: null,
    text_in_frame: "Premium Vodka — для настоящих ценителей",
    recommendation: "blur",
  },
];

const mockAnalysis: VideoAnalysis = {
  id: "analysis-1",
  video_title: "Фильм_пример_2024.mp4",
  duration: "00:35:00",
  analyzed_at: "2026-04-12",
  summary: {
    total_scenes: 12,
    risk_scenes: 8,
    critical_count: 5,
    warning_count: 2,
    info_count: 1,
    risk_categories: [
      "profanity",
      "violence",
      "smoking",
      "forbidden_symbols",
      "crime_glorification",
      "drugs",
      "alcohol",
    ],
  },
  scenes: mockScenes,
};

const mockAnalysis2: VideoAnalysis = {
  id: "analysis-2",
  video_title: "Сериал_S01E03.mp4",
  duration: "00:48:22",
  analyzed_at: "2026-04-11",
  summary: {
    total_scenes: 18,
    risk_scenes: 3,
    critical_count: 1,
    warning_count: 1,
    info_count: 1,
    risk_categories: ["profanity", "alcohol", "smoking"],
  },
  scenes: [
    {
      scene_number: 1,
      start_time: "00:00:00",
      end_time: "00:05:00",
      description: "Вступление, титры сезона",
      risk: null,
      risk_level: null,
      probability: null,
      reason: null,
      quote: null,
      text_in_frame: null,
      recommendation: null,
    },
    {
      scene_number: 2,
      start_time: "00:12:30",
      end_time: "00:14:10",
      description: "Персонаж нецензурно выражается в споре",
      risk: "profanity",
      risk_level: "critical",
      probability: 0.89,
      reason: "Использование нецензурной лексики",
      quote: "Да пошёл ты ******!",
      text_in_frame: null,
      recommendation: "mute",
    },
    {
      scene_number: 3,
      start_time: "00:28:00",
      end_time: "00:29:15",
      description: "Персонаж курит сигарету",
      risk: "smoking",
      risk_level: "warning",
      probability: 0.65,
      reason: "Демонстрация курения",
      quote: null,
      text_in_frame: null,
      recommendation: "shorten",
    },
  ],
};

export const mockFiles: VideoFile[] = [
  {
    id: "file-1",
    name: "Фильм_пример_2024.mp4",
    size: 450_000_000,
    status: "completed",
    progress: 100,
    project_id: "project-1",
    folder_id: "folder-1",
    analysis: mockAnalysis,
    created_at: "2026-04-10",
  },
  {
    id: "file-2",
    name: "Сериал_S01E01.mp4",
    size: 380_000_000,
    status: "completed",
    progress: 100,
    project_id: "project-1",
    folder_id: "folder-1",
    created_at: "2026-04-10",
  },
  {
    id: "file-3",
    name: "Сериал_S01E02.mp4",
    size: 410_000_000,
    status: "processing",
    progress: 67,
    project_id: "project-1",
    folder_id: "folder-1",
    created_at: "2026-04-11",
  },
  {
    id: "file-4",
    name: "Сериал_S01E03.mp4",
    size: 395_000_000,
    status: "completed",
    progress: 100,
    project_id: "project-1",
    folder_id: "folder-2",
    analysis: mockAnalysis2,
    created_at: "2026-04-11",
  },
  {
    id: "file-5",
    name: "Реклама_30сек.mp4",
    size: 25_000_000,
    status: "completed",
    progress: 100,
    project_id: "project-2",
    created_at: "2026-04-09",
  },
  {
    id: "file-6",
    name: "Трейлер_нового_сезона.mp4",
    size: 180_000_000,
    status: "queued",
    progress: 0,
    project_id: "project-2",
    created_at: "2026-04-12",
  },
  {
    id: "file-7",
    name: "Документальный_фильм.mp4",
    size: 500_000_000,
    status: "error",
    progress: 45,
    project_id: "project-3",
    created_at: "2026-04-08",
  },
  {
    id: "file-8",
    name: "Ток_шоу_выпуск_15.mp4",
    size: 320_000_000,
    status: "completed",
    progress: 100,
    project_id: "project-3",
    created_at: "2026-04-07",
  },
];

export const mockProjects: Project[] = [
  {
    id: "project-1",
    name: "Сериал «Перекрёсток»",
    folders: [
      { id: "folder-1", name: "Сезон 1", project_id: "project-1", files_count: 3 },
      { id: "folder-2", name: "Сезон 2", project_id: "project-1", files_count: 1 },
      { id: "folder-3", name: "Промо", project_id: "project-1", files_count: 0 },
    ],
    files: mockFiles.filter((f) => f.project_id === "project-1"),
    created_at: "2026-04-01",
  },
  {
    id: "project-2",
    name: "Рекламные ролики Q2",
    folders: [],
    files: mockFiles.filter((f) => f.project_id === "project-2"),
    created_at: "2026-04-05",
  },
  {
    id: "project-3",
    name: "Документальный цикл",
    folders: [],
    files: mockFiles.filter((f) => f.project_id === "project-3"),
    created_at: "2026-03-28",
  },
  {
    id: "project-4",
    name: "Ток-шоу «Вечер»",
    folders: [],
    files: [],
    created_at: "2026-03-20",
  },
  {
    id: "project-5",
    name: "Фильмы 2026",
    folders: [],
    files: [],
    created_at: "2026-03-15",
  },
  {
    id: "project-6",
    name: "Архив 2025",
    folders: [],
    files: [],
    created_at: "2025-12-01",
  },
];

export function getProjectById(id: string): Project | undefined {
  return mockProjects.find((p) => p.id === id);
}

export function getFileById(id: string): VideoFile | undefined {
  return mockFiles.find((f) => f.id === id);
}

export function getRecentFiles(): VideoFile[] {
  return [...mockFiles].sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  ).slice(0, 4);
}

export function getRiskyScenes(analysis: VideoAnalysis): Scene[] {
  return analysis.scenes.filter((s) => s.risk !== null);
}
